### ISSUE TITLE
Clear association between proportions and haplotypes

### ISSUE THREAD

**Issue by Ahhgust** [DEploid-dev/DEploid-r#55]
Hi!
I've testing out dEploid for some "off label" uses-- namely, for mitochondrial mixture deconvolution in forensics, and so far the results of your program are promising. I'm currently testing out the R interface as we already have a code-base in R and I was wondering if some aspects of the documentation could be more clear. For example, the R object returned from dEploid has some fields that could have a little more information on them. In particular, the $Haps matrix appears to have 1 row for each inferred haplotype-- I take it that 1 means the alternative allele, 0 means the reference? And the proportions matrix appears to give the mixture proportions for each round of the MCMC. How, then, are the mixture proportions re-associated back to the haplotype? In our test-case there's only three inferred haplotypes and five columns of proportions so the correspondence does not seem clear.
Regardless, I love the program so far!
-August

**Comment by shajoezhu** [comment]
Dear @Ahhgust 

Thanks for using our program! Can you take a look at the document at https://cran.r-project.org/web/packages/DEploid/vignettes/dEploid-Arguments.html 

Hope this provides some context for using the program R interface. The $Proportions records MCMC samples of the proportion, and please use the last entry as a point estimate. 

We fix the number of strains (5 as default), as the deconvolution proceeds, we drop the strains that has proportion below 0.01 (in the final iteration). E.g. if the last proportions are like 
0.3.   0.699     1.2e-4     1.2e-4   0.00076

There are then 2 strains with proportions of .3 and .7

Hope this helps!

Best
Joe

**Comment by Ahhgust** [comment]
Thanks for getting back to me so quickly!
In your example, I would have inferred two haplotypes and two haplotype frequencies-- how do these values correspond?  e.g., how would I know which haplotype was at frequency 0.3? Is the ordering maintained?

**Comment by shajoezhu** [comment]
@Ahhgust Yes, the ordering is maintained.
